ERROR in node_modules/angular-4-data-table/src/components/header.component.ts(8,13): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.     node_modules/angular-4-data-table/src/components/pagination.component.ts(8,15): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.     node_modules/angular-4-data-table/src/components/row.component.ts(10,15): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.     node_modules/angular-4-data-table/src/components/table.component.ts(16,12): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.     node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.     node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.     src/app/admin-auth-guard.service.ts(1,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.     src/app/admin/admin-products/admin-products.component.ts(2,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.     src/app/admin/admin-products/admin-products.component.ts(21,8): error TS2339: Property 'subscribe' does not exist on type 'AngularFireList<{}>'.     src/app/admin/product-form/product-form.component.ts(26,51): error TS2339: Property 'take' does not exist on type 'AngularFireObject<{}>'.     src/app/auth.service.ts(4,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.     src/app/bs-navbar/bs-navbar.component.ts(2,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.     src/app/category.service.ts(11,7): error TS2345: Argument of type '{ query: { orderByChild: string; }; }' is not assignable to parameter of type 'QueryFn'.       Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.     src/app/check-out/check-out.component.ts(1,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.     src/app/order.service.ts(22,7): error TS2345: Argument of type '{ query: { orderByChild: string; equalTo: string; }; }' is not assignable to parameter of type 'QueryFn'.       Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.     src/app/products/products.component.ts(2,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.     src/app/products/products.component.ts(36,8): error TS2339: Property 'switchMap' does not exist on type 'AngularFireList<{}>'.     src/app/shipping-form/shipping-form.component.ts(5,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.     src/app/shopping-cart.service.ts(1,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.     src/app/shopping-cart.service.ts(4,31): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/angularfire2/database"' has no exported member 'FirebaseObjectObservable'.     src/app/shopping-cart.service.ts(17,8): error TS2339: Property 'map' does not exist on type 'AngularFireObject<{}>'.     src/app/shopping-cart.service.ts(56,11): error TS2339: Property 'take' does not exist on type 'AngularFireObject<{}>'.     src/app/user.service.ts(2,31): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/angularfire2/database"' has no exported member 'FirebaseObjectObservable'.
    ERROR in node_modules/angular-4-data-table/src/components/header.component.ts(8,13): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
    node_modules/angular-4-data-table/src/components/pagination.component.ts(8,15): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
    node_modules/angular-4-data-table/src/components/row.component.ts(10,15): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
    node_modules/angular-4-data-table/src/components/table.component.ts(16,12): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
    node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
    node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
    src/app/admin-auth-guard.service.ts(1,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.
    src/app/admin/admin-products/admin-products.component.ts(2,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
    src/app/admin/admin-products/admin-products.component.ts(21,8): error TS2339: Property 'subscribe' does not exist on type 'AngularFireList<{}>'.
    src/app/admin/product-form/product-form.component.ts(26,51): error TS2339: Property 'take' does not exist on type 'AngularFireObject<{}>'.
    src/app/auth.service.ts(4,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.
    src/app/bs-navbar/bs-navbar.component.ts(2,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.
    src/app/category.service.ts(11,7): error TS2345: Argument of type '{ query: { orderByChild: string; }; }' is not assignable to parameter of type 'QueryFn'.
      Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
    src/app/check-out/check-out.component.ts(1,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.
    src/app/order.service.ts(22,7): error TS2345: Argument of type '{ query: { orderByChild: string; equalTo: string; }; }' is not assignable to parameter of type 'QueryFn'.
      Object literal may only specify known properties, and 'query' does not exist in type 'QueryFn'.
    src/app/products/products.component.ts(2,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.
    src/app/products/products.component.ts(36,8): error TS2339: Property 'switchMap' does not exist on type 'AngularFireList<{}>'.
    src/app/shipping-form/shipping-form.component.ts(5,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
    src/app/shopping-cart.service.ts(1,10): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/rxjs/Observable"' has no exported member 'Observable'.
    src/app/shopping-cart.service.ts(4,31): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/angularfire2/database"' has no exported member 'FirebaseObjectObservable'.
    src/app/shopping-cart.service.ts(17,8): error TS2339: Property 'map' does not exist on type 'AngularFireObject<{}>'.
    src/app/shopping-cart.service.ts(56,11): error TS2339: Property 'take' does not exist on type 'AngularFireObject<{}>'.
    src/app/user.service.ts(2,31): error TS2305: Module '"F:/Github Vs Code/Shopping-Cart-System-using-Angular-8-Auth-Module-Firebase/shop/node_modules/angularfire2/database"' has no exported member 'FirebaseObjectObservable'.